pages/urls.py
from django.urls import path

from .views import AboutPageView, HomePageView

app_name = "pages"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="list"),
    path("<slug:slug>/", views.ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", views.ProductListView.as_view(), name="list_by_category"),
]

pystore/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('products/', include("products.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

pages/models.py
from django.db import models

# Create your models here.

products/models.py
from autoslug import AutoSlugField
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel


class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)


class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:list_by_category", kwargs={"slug": self.slug})


class Product(TimeStampedModel):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})

users/models.py
from django.contrib.auth import models


class User(models.AbstractUser):
    pass

users/forms.py
from django.contrib.auth import forms

from.models import User


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"


class AboutPageView(TemplateView):
    template_name = "about.html"

products/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from .models import Category, Product


class ProductDetailView(DetailView):
    queryset = Product.available.all()


class ProductListView(ListView):
    category = None
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.available.all()

        category_slug = self.kwargs.get("slug")
        if category_slug:
            self.category = get_object_or_404(Category, slug=category_slug)
            queryset = queryset.filter(category=self.category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        context["categories"] = Category.objects.all()
        return context

users/views.py
from django.shortcuts import render

# Create your views here.

templates/about.html
{% extends 'base.html' %}

{% block title %}Sobre Nós{% endblock title %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Sobre nós</h1>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, totam iure numquam quaerat amet, officiis
        accusantium dolor assumenda dolores esse dignissimos voluptatem. Commodi laborum non minima dolor illum
        reiciendis est.Temporibus delectus quam odit voluptatibus debitis nesciunt optio voluptates ut inventore porro
        perferendis, quidem magnam repellat quo ratione, quos quod? Nesciunt, in quidem. Necessitatibus sapiente ad iure
        impedit quod cumque?
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur laborum nam aliquid nostrum a omnis temporibus
        deserunt fugit similique quod? Aliquam, eius quos quam laudantium ea deserunt consectetur magnam
        soluta.Accusamus enim fugit voluptatem, quasi, labore tempora adipisci magni ea voluptatum culpa recusandae qui
        reiciendis maiores ratione animi velit corrupti sequi ab eum placeat. Voluptatem quaerat nesciunt reiciendis
        aperiam vero.
    </p>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">

{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}Loja Python{% endblock title %}</title>
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-sm py-3 border-bottom navbar-light">
        <div class="container">
            <a href="{% url 'pages:home' %}" class="navbar-brand">
                <span class="font-weight-bold h3">Loja Python</span>
            </a>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="{% url 'products:list' %}" class="nav-link lead mr-4 font-weight-bold">Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'pages:about' %}" class="nav-link lead mr-4 font-weight-bold">Sobre Nós</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Olá!</h1>
    <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur autem beatae saepe at nulla accusamus,
        mollitia quibusdam laborum, voluptatem corporis molestiae ipsa, id quasi distinctio deserunt et. Ipsam, dolorem
        quidem.Itaque, magnam explicabo! Corrupti eos optio repellat debitis omnis voluptates laudantium fuga dolore
        incidunt autem. Veritatis harum sunt eveniet sequi, impedit quaerat modi assumenda recusandae molestias adipisci
        laborum cumque ad.
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid non porro temporibus, unde pariatur sit
        doloremque molestiae fugit, nostrum, atque beatae praesentium vero deserunt aspernatur cumque culpa reiciendis
        corrupti dolores!Illum ratione enim repellendus quas? Inventore at aut aliquid minus pariatur facilis id
        adipisci consequuntur soluta doloremque. Sit quae quisquam quis molestiae similique esse natus atque saepe rem
        placeat? Nostrum?
    </p>
</div>

{% endblock content %}

templates/pagination.html
<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    Página {{ page.number }} de {{ page.paginator.num_pages }}.
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Próxima</a>
    {% endif %}
</div>

templates/products/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ product.name }}{% endblock title %}

{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col-lg-3 mb-3 mb-lg-0">
            {% if product.image %}
            <img class="container-fluid" src="/media/{{product.image}}" alt="">
            {% else %}
            <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
            {% endif %}
        </div>
        <div class="col-lg-9">
            <h1 class="font-weight-bold">{{ product.name }}</h1>
            <h2>R$ {{ product.price }}</h2>
            <p>{{ product.description }}</p>
            <p>
                Voltar para o catálogo de
                <a class="text-decoration-none" href="{{ product.category.get_absolute_url }}">
                    {{ product.category.name }}
                </a>
            </p>
        </div>
    </div>
</div>

{% endblock content %}

templates/products/product_list.html
{% extends 'base.html' %}

{% load static %}
{% load product_tags %}

{% block title %}
{% if category %}
{{ category.name }}
{% else %}
Produtos
{% endif %}
{% endblock title %}

{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col-lg-3">
            <ul class="list-group mb-3 mb-lg-0">
                <a class="text-decoration-none list-group-item list-group-item-light {% if not category %}active{% endif %}"
                    href="{% url 'products:list' %}">
                    Todos os produtos
                </a>

                {% for cat in categories %}
                <a class="text-decoration-none list-group-item list-group-item-light {% if category == cat %}active{% endif %}"
                    href="{{ cat.get_absolute_url }}">
                    {{ cat.name }}
                </a>
                {% endfor %}
            </ul>
        </div>
        <div class="col-lg-9">
            <div class="card-deck mb-3">
                {% for product in product_list %}
                <div class="card">
                    <a href="{{ product.get_absolute_url }}">
                        {% if product.image %}
                        <img class="card-img-top" src="/media/{{product.image}}" alt="">
                        {% else %}
                        <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
                        {% endif %}
                    </a>

                    <div class="card-body d-flex flex-column justify-content-between">
                        <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                            <h5 class="card-title">{{ product.name }}</h5>
                        </a>
                        <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                            <p class="card-text font-weight-bold">R$ {{ product.price }}</p>
                        </a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div>
            <div class="card-deck mb-3">
                {% endif %}
                {% endfor %}

                {% if product_list|length|remainder == 2 %}
                <div class="card border-0"></div>
                {% elif product_list|length|remainder == 1 %}
                <div class="card border-0"></div>
                <div class="card border-0"></div>
                {% endif %}
            </div>

            {% if is_paginated %}
            {% include "pagination.html" with page=page_obj %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}